README.md
Oi Pedro, 
Este é o meu primeiro commit. Estou apenas testando se o remote está funcionando corretamente. 
Fiz apenas uma pequena modificação no arquivo README.md dando uma breve explicação sobre o projeto no qual estamos trabalhando. 
Mais tarde podemos escrever mais e oferecer uma explicação mais detalhada sobre o que o projeto faz ;) 
Beijos!
=> first draught on readme.md

Gemfile, Gemfile.lock, config/database.yml, db/schema.rb
Oi @zzismano : 
Como conversamos pelo slack, nós precisávamos mudar a base de dados de sqlite3 para postgresql. 
eu já fiz as modificações necessárias: 
- Instalei a gem postgresql
- Alterei os dados de configuração da base de dados no config/database.yml
- Testei a DB no console do rails. Até este momento tudo parece estar funcionando bem. 
Aguardo sua aprovação,
=> PostgreSQL DB Setup

.gitignore, Gemfile, Gemfile.lock, config/environments/development.rb, config/environments/production.rb, config/storage.yml, db/migrate/20240514160024_create_active_storage_tables.active_storage.rb, db/schema.rb
Hello @zzismano ,
Segue o setup básico para o image hosting / cloudinary. 
Eu segui a instalação padrão, migrei o active storage e está tudo pronto para adicionarmos a associação has_photo nos models. 
Até agora configuração padrão. 
Abs,
=> Cloudinary Setup

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/leisures_controller.rb, app/policies/application_policy.rb, app/policies/leisure_policy.rb, test/policies/leisure_policy_test.rb
Last push of the day!
- installed pundit, 
- set up the application policy,
- generated a Leisure policy
- defined scope for leisures#index ? still need become one with the pundit
Cheerio! (nothing is breaking)
=> pundit startup

app/policies/category_policy.rb, app/policies/genre_policy.rb, app/policies/venue_policy.rb, db/schema.rb, test/policies/category_policy_test.rb, test/policies/genre_policy_test.rb, test/policies/venue_policy_test.rb
Hi @zzismano, 
As we previously agreed I generated all pundit policies for the app.
=> Pundit Policies Generated For All Models

Gemfile, Gemfile.lock, app/controllers/leisures_controller.rb, app/views/layouts/application.html.erb, app/views/leisures/new.html.erb, config/initializers/simple_form.rb, config/initializers/simple_form_bootstrap.rb, config/locales/simple_form.en.yml, config/routes.rb, lib/templates/erb/scaffold/_form.html.erb
@cvaldivia83,
- added the index, new and create routes for leisure using resources
- installed simple form and created the new leisure form using it
- disabled country select from simple form
- disabled the pundit error raised in development environment
=> index new and create routes for leisure

Gemfile, Gemfile.lock, app/controllers/categories_controller.rb, app/controllers/genres_controller.rb, app/controllers/leisures_controller.rb, app/controllers/venues_controller.rb, app/policies/application_policy.rb, app/policies/category_policy.rb, app/policies/genre_policy.rb, app/policies/leisure_policy.rb, app/policies/venue_policy.rb, app/views/categories/new.html.erb, app/views/genres/new.html.erb, app/views/leisures/new.html.erb, app/views/venues/new.html.erb, config/environments/development.rb, config/routes.rb
hi @cvaldivia83!
In order to create a leisure there already must exist venues, genres and categories. So, I went ahead and coded the New and Create for everything. It's all working fine, except I noticed that I forgot to include genre as an attribute of leisure D:
Next step: create a migration adding genres to leisures.
=> New leisure

app/models/leisure_genre.rb, db/migrate/20240517135033_create_leisure_genres.rb, db/schema.rb, test/fixtures/leisure_genres.yml, test/models/leisure_genre_test.rb
Oi Carla!
Criei o Model de LeisureGenre e fiz a migração. O site tá rodando.
=> Genre migration

app/views/categories/new.html.erb, app/views/genres/new.html.erb, app/views/leisures/new.html.erb, app/views/venues/new.html.erb
I just refactored categories, venues, and genres forms so that they would have the same front end. 
Att,
=> Refactor categories, venues, genre forms

db/migrate/20240520151813_add_user_to_venues.rb, db/migrate/20240520151911_add_user_to_genres.rb, db/migrate/20240520151946_add_user_to_categories.rb, db/migrate/20240520151957_add_user_to_leisures.rb, db/schema.rb, db/seeds.rb
I just updated our schema to include a user foreign key on the tables Venues, Genres, Categories and Leisures. 
I haven't updated the forms or the controllers yet. I will update forms and controlllers in the next PR, as well as the edit forms. 
Att,
=> User foreign key in venues, categories, genres and leisures

app/models/category.rb, app/models/genre.rb, app/models/leisure.rb, app/models/user.rb, app/models/venue.rb
eu ja adicionei as associacoes e ja testei com o seed. tudo esta funcionando ;) 
Att,
=> Add user associations to venues, genres, categories and leisures

app/controllers/categories_controller.rb, app/controllers/genres_controller.rb, app/controllers/venues_controller.rb, app/policies/category_policy.rb, app/policies/genre_policy.rb, app/policies/venue_policy.rb, app/views/categories/index.html.erb, app/views/genres/index.html.erb, app/views/leisures/dashboard.html.erb, app/views/venues/index.html.erb, config/routes.rb
=> Dashboard2

app/controllers/leisure_genres_controller.rb, app/helpers/leisure_genres_helper.rb, app/policies/leisure_genre_policy.rb, app/views/leisure_genres/new.html.erb, app/views/leisures/dashboard.html.erb, config/routes.rb, test/controllers/leisure_genres_controller_test.rb
Criada e autorizada funcao de eletar leisure_genres...
=> leisure genre deletável

app/models/leisure.rb, app/models/leisure_venue.rb, app/models/venue.rb, db/migrate/20240521183319_create_leisure_venues.rb, db/migrate/20240521183834_remove_venue_from_leisure.rb, db/schema.rb, db/seeds.rb, test/fixtures/leisure_venues.yml, test/models/leisure_venue_test.rb
Hey @zzismano, 
Just sending our latest code: 
- 1 new model - LeisureVenue
- 1 new table - leisures_venues
- 1 migration to remove venue_id from leisures table
- New associations between leisures and venues through leisure_venues
- Seeds updated to include the new join table
I tested the new model and associations and everything is working Ok. 
Att,
=> Leisures venues

app/controllers/genres_controller.rb, app/controllers/leisure_venues_controller.rb, app/controllers/leisures_controller.rb, app/controllers/venues_controller.rb, app/models/leisure.rb, app/models/venue.rb, app/policies/leisure_venue_policy.rb, app/policies/venue_policy.rb, app/views/categories/index.html.erb, app/views/leisures/dashboard.html.erb, app/views/leisures/new.html.erb, config/routes.rb, db/schema.rb
Hi @cvaldivia83 ,
today was tough, but we made it!
join tables ready, leisure_genres and leisure_venues created alongside the leisures.
=> join tables working

Gemfile
=> Revert "country select gem"

app/views/leisures/index.html.erb
Segue um fix da parte do country select que estava bugando o projeto do meu lado.
=> Fix country select implementation on leisures index

app/controllers/leisures_controller.rb
oi, carla!
isto permite apenas tentar criar leisure_genres e leisure_venues caso tenham sido escolhidos genres ou venues no formulario
=> leisure sem venue e genre bug

app/models/venue.rb, app/views/leisures/index.html.erb, app/views/leisures/new.html.erb, db/seeds.rb
Hey @zzismano,
Finalmente achei o erro. Os Seeds estavam criando leisures com países com o nome completo.
Ao dar o rails s o country-select nao conseguia ler o país e transformar na sigla com 3 letras. 
Já fiz update no seeds e também no formulário para que o campo seja um select. 
Att,
=> Country final fix

app/controllers/leisures_controller.rb, app/helpers/errors_helper.rb, app/views/leisures/new.html.erb, db/migrate/20240528182524_add_zone_to_leisures.rb, db/schema.rb, db/seeds.rb
oi @cvaldivia83!
-inclui uma migration para adicionar zone em leisures
-modifiquei as seeds para incluir zonas
-modifiquei o controller de leisure para permit :zone
-incluí no form.
PS.: Inclui no commit sem querer u m arquivo de errors helper. eu tava tentando criar uma mensagem de erro customizada pra quando alguém não está autorizado, mas desisti de fazer, e acabou sobrando essa file... acho que não deve atrapalhar
=> zona no leisure

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_sidebar.scss, app/controllers/cards_controller.rb, app/helpers/cards_helper.rb, app/models/card.rb, app/models/leisure.rb, app/policies/application_policy.rb, app/policies/card_policy.rb, app/views/cards/_list.html.erb, app/views/cards/card_config.html.erb, app/views/cards/new.html.erb, app/views/layouts/application.html.erb, app/views/leisures/dashboard.html.erb, app/views/shared/_flashes.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_sidebar.html.erb, config/routes.rb, db/migrate/20240531022322_create_cards.rb, db/schema.rb, db/seeds.rb, test/controllers/cards_controller_test.rb, test/fixtures/cards.yml, test/models/card_test.rb, test/policies/card_policy_test.rb
Hello @zzismano , 
Segue a primeira versão do componente Cards. Para esta primeira etapa eu fiz: 
- Card model
- Cards Controller
- Cards Policy
- New, create, destroy actions no cards controller
- Index view dos cards
- SCSS do card para filmes
Aproveitando o embalo, também comecei a adicionar pequenas adições de outras features que virão nesta semana: 
- Adicionei o sidebar html & CSS. Ainda nao importei o JS pois precisamos discutir como proceder. 
- Adicionei a tag main no application.html.erb para começar com a revisão da acessibilidade do site amanhã. 
Acho que por enquanto é isso.
=> Cards Component

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_leisure.scss, app/assets/stylesheets/config/_fonts.scss, app/views/leisures/index.html.erb
ajustes de front-end.
Mexi no botao de comprar ingresso, e na font-family geral. 
também, a classe css dos elementos do html variam de acordo com a categoria do leisure
=> botão e fontes

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_musica.scss, app/assets/stylesheets/components/_teatro.scss, app/controllers/venues_controller.rb, app/views/shared/_musica.html.erb, app/views/shared/_teatro.html.erb, db/seeds.rb
Bom dia, @cvaldivia83.
Criei partials e css separados para as categorias musica filme e teatro, com diferenciações entre si, e inclui um leisure de musica nos seeds.
=> leisures separados e seeds atualizados

app/controllers/leisures_controller.rb, app/javascript/controllers/selector_controller.js, app/views/genres/new.html.erb, app/views/leisures/dashboard.html.erb, app/views/leisures/index.html.erb, app/views/leisures/new.html.erb, app/views/shared/_sidebar.html.erb, app/views/venues/new.html.erb, config/initializers/simple_form.rb
implementei um stimulus controller pra o funcionamento da barra lateral
=> sidebar expandindo mas não filtrando

app/controllers/leisures_controller.rb, app/policies/leisure_policy.rb, app/views/leisures/filme_filter.html.erb, app/views/leisures/index.html.erb, app/views/leisures/musica_filter.html.erb, app/views/leisures/teatro_filter.html.erb, app/views/shared/_sidebar.html.erb, config/routes.rb
Boa noite @cvaldivia83 
Encontrei um jeito de printar os leisures por categoria numa turbo frame, clicando na sidebar. Desta forma é necessário manter as categorias sempre as mesmas e não criar novas. mas pelo menos está funcionando.
https://github.com/zzismano/jae_rails/assets/111464708/eeb66acf-27e9-4c92-bc46-933585514cdd
=> filtro de categorias para musica teatro e filme

app/views/shared/_sidebar.html.erb
Apenas conectei o stimulus controller aos elementos da sidebar.
=> stimulus controleer conectado

app/controllers/leisures_controller.rb, app/controllers/venues_controller.rb, app/models/leisure.rb, app/views/leisures/new.html.erb, app/views/venues/edit.html.erb, app/views/venues/index.html.erb, app/views/venues/new.html.erb, db/migrate/20240619180053_remove_zone_from_leisures.rb, db/migrate/20240619180129_add_zone_to_venues.rb, db/schema.rb, db/seeds.rb
Olá, @cvaldivia83 !
Zonas:
- Adicionei migrations pra remover a coluna de zone da leisures table, e acrescentá-la à venues table
- Modifiquei as seeds para contemplar esta mudança
- Aproveitei e melhorei os gêneros nas seeds
- Fiz as modificações necessárias aos formulários para criar e editar leisures e venues contemplando a questão da zona
- acrescentei uma coluna à lista de venues contemplando a zona
Validação: 
- Adicionei uma validação de length no leisure model para a description.
=> retificação de zona, e validação de sinopse

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_expo.scss, app/assets/stylesheets/components/_filme.scss, app/assets/stylesheets/components/_leisure.scss, app/assets/stylesheets/components/_musica.scss, app/assets/stylesheets/components/_sidebar.scss, app/assets/stylesheets/components/_teatro.scss, app/views/leisures/new.html.erb, app/views/shared/_expo.html.erb, app/views/shared/_filme.html.erb, app/views/shared/_sidebar.html.erb, config/environments/production.rb, lib/tasks/scheduler.rake
Mudanças nos cards, sidebar, criação de task
=> Leisure cards format

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_colors.scss, app/views/shared/_navbar.html.erb, db/seeds.rb
Como recebemos as novas modificacoes da cliente aproveitei e deixei a navbar seguindo o pedido: 
- Adicionei variáveis de cor no arquivo config/colors.scss com todas as cores especificadas pela cliente no prototipo.
- Alterei a cor do background para branco
- Alterei a cor das letras para a cor vinho característica do site
- Alterei o avatar com a foto do ssaunier para o logo jae. E uma alteracao temporaria. Eu estava testando colocando o menu sanduiche e tive problemas com o bootstrap. Talvez tenhamos que refazer o menu. A ser visto
- Adicionei a borda vinho na parte de baixo do menu
- Adicionei um input de busca como pedido. 
Como as modificações são apenas no front end e com poucas alterações vou mergear o PR ok?
=> Add new changes to navbar

app/assets/stylesheets/components/_sidebar.scss, app/javascript/controllers/selector_controller.js, app/views/shared/_sidebar.html.erb
Hello @zzismano ,
Fiz pequenas adaptações no sidebar para que ele ficasse da maneira que a cliente mandou no prototipo: 
- Apliquei as cores do protótipo
- Adicionei uma pequena margem entre cada botão
- Ela adicionou mais 2 categorias no protótipo: dança e festa. Acho que precisamos conversar com ela sobre diminuirmos as categorias porque o sidebar ficou gigante. Ele ultrapassa o height do viewport e me vi obrigada a retirar os icones porque eles nem estavam sendo printados. Acho que precisamos conversar com ela sobre a altura do sidebar e suas limitacoes. 
- Ajustei o stimulus controller para caber mais essas duas categorias. Mas mais uma vez, temos que ver com ela de talvez tirar. 
Como só dei um tapa no front end, vou aproveitar e dar merge ok?
=> Sidebar colors

app/models/leisure.rb, app/views/cards/_list.html.erb, app/views/leisures/edit.html.erb, app/views/leisures/new.html.erb, app/views/shared/_danca.html.erb, app/views/shared/_evento.html.erb, app/views/shared/_expo.html.erb, app/views/shared/_festa.html.erb, app/views/shared/_filme.html.erb, app/views/shared/_musica.html.erb, app/views/shared/_teatro.html.erb, db/migrate/20240703182051_remove_publish_date_from_leisures.rb, db/migrate/20240703182246_add_schedule_to_leisures.rb, db/migrate/20240703182555_remove_time_from_leisures.rb, db/migrate/20240703183135_add_date_to_leisures.rb, db/schema.rb, db/seeds.rb
@cvaldivia83 ,
**Mudanças no schema:**
- Mantive o start_date e end_date para respectivamente poder programar a publicação e destruição dos leisures e hidden para ocultar se bem entender.
- Removi o published_date e o time.
- Acrescentei schedule para os horários (Ex.: "seg a qui 20h | dom 19") e date para a data (ex.: "27/jul a 20/ago").
**Mudanças no front:**
- Modifiquei os partials de leisure pra acomodar essas mudanças, inclusive os cards das sections.
**Seeds:**
- acrescentei um Section.Destroy_all no começo da seeds.rb e modifiquei os leisures para contemplarem as mudanças no schema.
=> mudanças nas datas

app/views/cards/_list.html.erb, app/views/sections/_index.html.erb, app/views/sections/_list.html.erb
Boa noite, @cvaldivia83 
Dei pull no ultimo e reparei que estava dando erro com os cards e sections, pq tinha faltado readequa-los ao novo modelo de hora e data. fiz as correções e agora parece estar tudo funcionando.
Abs.
=> readequando cards e sections com novas datas e horarios

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_carousel.scss, app/assets/stylesheets/components/_main.scss, app/assets/stylesheets/components/_sidebar.scss, app/assets/stylesheets/config/_colors.scss, app/views/banners/_show.html.erb, app/views/cards/_list.html.erb, app/views/leisures/home.html.erb, app/views/leisures/index.html.erb, app/views/sections/_list.html.erb, app/views/shared/_header.html.erb, app/views/shared/_newsletter.html.erb, app/views/shared/_search_links.html.erb
hi @cvaldivia83,
mexi em bastante coisa do front-end. Tá mais preoximo do que a cliente quer, mas é um ecossistema frágil :,), imagino que quando vc for mexer na sidebar vai ser uma baita diversão :)  🔥 🧯
=> new home page layout, some responsiveness and sections layout

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_danca.scss, app/assets/stylesheets/components/_expo.scss, app/assets/stylesheets/components/_festa.scss, app/assets/stylesheets/components/_filme.scss, app/assets/stylesheets/components/_leisure.scss, app/assets/stylesheets/components/_musica.scss, app/assets/stylesheets/components/_sidebar.scss, app/assets/stylesheets/components/_teatro.scss, app/assets/stylesheets/config/_colors.scss, app/views/cards/_list.html.erb, app/views/layouts/application.html.erb, app/views/leisures/index.html.erb, app/views/sections/_index.html.erb, app/views/shared/_danca.html.erb, app/views/shared/_evento.html.erb, app/views/shared/_expo.html.erb, app/views/shared/_festa.html.erb, app/views/shared/_filme.html.erb, app/views/shared/_header.html.erb, app/views/shared/_musica.html.erb, app/views/shared/_search_links.html.erb, app/views/shared/_teatro.html.erb
oi @cvaldivia83. Aqui estão mudanças de front (section cards, e cards normais)
=> Smaller container

app/assets/stylesheets/components/_card.scss, app/controllers/leisures_controller.rb, app/models/card.rb, app/views/leisures/index.html.erb, app/views/sections/_index.html.erb, app/views/shared/_danca.html.erb, app/views/shared/_evento.html.erb, app/views/shared/_expo.html.erb, app/views/shared/_festa.html.erb, app/views/shared/_filme.html.erb, app/views/shared/_musica.html.erb, app/views/shared/_teatro.html.erb
Consertos nos leisure params incluindo schedule e date
ajuste nas imagens dos cards para nao deformar
conserto no section_card delete path
conserto no link de comprar ingresso
=> Ticket link

app/assets/stylesheets/components/_navbar.scss, app/views/cards/_list.html.erb, app/views/leisures/edit.html.erb, app/views/leisures/new.html.erb, app/views/sections/_index.html.erb, app/views/sections/_list.html.erb, app/views/shared/_filme.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_sidebar.html.erb, app/views/shared/_teatro.html.erb
Adaptação de navbar,
correção de subcategorias placeholder
atualização dos forms (faixa etária como collection, inclusão de free no edit)
& outros pequenos ajustes
=> client fixes

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_carousel.scss, app/assets/stylesheets/components/_main.scss, app/assets/stylesheets/components/_mais.scss, app/assets/stylesheets/components/_sidebar.scss, app/assets/stylesheets/config/_colors.scss, app/controllers/genres_controller.rb, app/controllers/venues_controller.rb, app/policies/genre_policy.rb, app/policies/venue_policy.rb, app/views/leisures/home.html.erb, app/views/leisures/index.html.erb, app/views/sections/_list.html.erb, app/views/shared/_header.html.erb, app/views/shared/_mais.html.erb, app/views/shared/_sidebar.html.erb, config/routes.rb
Homepage alinhada
section e cards menores, banner maior
=> Client fixes 2

app/assets/stylesheets/components/_sidebar.scss, app/controllers/leisures_controller.rb, app/javascript/controllers/selector_controller.js, app/javascript/controllers/subcategory_selector_controller.js, app/services/search_service.rb, app/views/shared/_sidebar.html.erb
subcategoria selecionada fica sublinhada, e as outras não.
=> subcategory select

app/views/shared/_danca.html.erb, app/views/shared/_musica.html.erb, app/views/shared/_teatro.html.erb
Updated the _danca.html.erb, _musica.html.erb, and _teatro.html.erb files to display a "Gratuito" label for free leisure events. This enhancement improves user experience by clearly indicating free options.
=> Add free event indicator to leisure views
